apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: hhvm
  name: hhvm
spec:
  output:
    to:
      kind: ImageStreamTag
      name: hhvm:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-wordpress-hhvm.git
    contextDir: hhvm/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: hhvm-webserver:latest
        namespace: weepee-registry
    type: Docker
